version: '3'
services:
  lauren-weaver:
    container_name: laren-weaver
    image: laren-weaver
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development